#! /usr/bin/python3

import sys
import datetime
sys.path.append('/usr/share/copr/coprs_frontend/')

import argparse
from coprs import models, db, helpers, app

import logging
logging.basicConfig()
log = logging.getLogger()

whitelist_fixes = [
    'sig',
    'group',
    'grp',
    'project',
    'team',
]

description = """
Create copr group, seemingly to be user (without '@' prefix).
"""
parser = argparse.ArgumentParser(
    prog='copr-new-usergroup',
    description=description,
)
parser.add_argument(
    "name",
    help="name of the group")

parser.add_argument(
    "email",
    help="email to the main contact, list, etc.")

args = parser.parse_args()

if not filter(lambda x : args.name.endswith("-" + x), whitelist_fixes) and \
   not filter(lambda x : args.name.startswith(x + "-"), whitelist_fixes):
    log.error("name must start/end with " + str(whitelist_suffixes))
    sys.exit(1)

user = models.User()
user.mail = args.email
user.username = args.name
user.api_login = "bot-" + args.name
user.api_token = helpers.generate_api_token()
user.api_token_expiration = datetime.date.today() + datetime.timedelta(days=365*20)

db.session.add(user)
db.session.commit()

token_template = """\
[copr-cli]
login = {api_login}
username = {user_name}
token = {api_token}
copr_url = {copr_url}"""

token = token_template.format(
    api_login=user.api_login,
    api_token=user.api_token,
    user_name=user.username,
    copr_url='https://' + app.config['PUBLIC_COPR_HOSTNAME'],
)

print(token)
